### ISSUE TITLE
想請問server端的問題

### ISSUE THREAD

**Issue by Mudboyzh** [tonytonyjan/guest-chat#5]
大兜你好
想試著重頭做看看聊天室的功能
但我在server那邊進行db的操作 像是
room = Room.find_by! handshake.path.sub('/','')
都會出現 ：uninitialized constant Room (NameError)
感覺像是抓不到db東西
想請問是不是要額外做設定？

**Comment by tonytonyjan** [comment]
你是在 `irb` 還是在 `rails console` 下操作？不是抓不到 db，是抓不到 `room.rb`

**Comment by Mudboyzh** [comment]
在rails console下是可以操作
但是在server.rb 這裡面無法操作
我把server.rb跟你一樣放在lib之下

**Comment by tonytonyjan** [comment]
你如果直接執行 `server.rb`，請試著用 rails run`

**Comment by Mudboyzh** [comment]
成功抓取了 ！！
謝謝大兜
